import { NextRequest, NextResponse } from 'next/server';
import { requireAuth } from '@/lib/auth/session';
import { ok, error } from '@/lib/api/response';
import { toAppError } from '@/lib/errors';
import { validateBody } from '@/lib/validation/middleware';
import { createOrderFromBookingsBodySchema } from '@/lib/validation/sale.schemas';
import { bookingRepository } from '@/server/repositories/booking.repository';
import { logActivity } from '@/server/services/activity.service';

/**
 * POST /api/sale/orders/from-bookings
 *
 * Converts an explicit set of CONFIRMED `Booking` rows for one customer in
 * one live session into a single `Order` with consolidated `OrderItem` rows.
 *
 * Idempotent: same body (same `bookingIds`) returns the existing Order
 * once it has been created. Built on `Booking.idempotencyKey` /
 * `Order.idempotencyKey` deterministic key:
 *   sale-conv:{shopId}:{liveSessionId}:{customerId}:{sortedBookingIdsHash16}
 *
 * Auth: OWNER or MANAGER only. CHAT_SUPPORT and WAREHOUSE forbidden per
 * RBAC §9 in dissent doc 2026-04-06-sale-mvp-dissent.md.
 *
 * No customer-facing message is generated by this route. Phase 1 = no
 * auto-send (Boss decision Q7). Future Commit 2J+ will add a separate
 * summary endpoint that returns localized text for admin to copy/preview.
 *
 * Repository contract:
 *   src/server/repositories/booking.repository.ts → convertToOrder()
 *
 * Design refs:
 * - docs/superpowers/2026-05-09-booking-to-order-conversion-dissent.md
 * - docs/superpowers/2026-04-06-sale-mvp-dissent.md
 */
export async function POST(request: NextRequest): Promise<NextResponse> {
  try {
    const user = await requireAuth();

    if (!user.shopId) {
      return NextResponse.json(error('No shop associated with your account'), {
        status: 403,
      });
    }

    if (!['OWNER', 'MANAGER'].includes(user.role)) {
      return NextResponse.json(error('Insufficient permissions'), { status: 403 });
    }

    const bodyResult = await validateBody(request, createOrderFromBookingsBodySchema);
    if ('error' in bodyResult) return bodyResult.error;

    const { liveSessionId, customerId, bookingIds } = bodyResult.data;

    const result = await bookingRepository.convertToOrder({
      shopId: user.shopId,
      liveSessionId,
      customerId,
      changedById: user.id,
      bookingIds,
    });

    // Activity log only on real conversion (not idempotent re-call) per
    // existing pattern (see /api/sale/bookings/.../confirm route).
    if (!result.idempotent) {
      logActivity({
        shopId: user.shopId,
        userId: user.id,
        userName: user.name,
        action: 'ORDER_CREATED_FROM_BOOKINGS',
        entity: 'order',
        entityId: result.orderId,
        description: `Order ${result.orderNumber} created from ${result.bookingCount} confirmed booking(s)`,
        metadata: {
          orderId: result.orderId,
          orderNumber: result.orderNumber,
          bookingCount: result.bookingCount,
          bookingIds: [...result.bookingIds],
          totalAmount: result.totalAmount,
          liveSessionId,
          customerId,
        },
      }).catch(() => {});
    }

    return NextResponse.json(
      ok({
        orderId: result.orderId,
        orderNumber: result.orderNumber,
        status: result.status,
        idempotent: result.idempotent,
        bookingCount: result.bookingCount,
        bookingIds: [...result.bookingIds],
        totalAmount: result.totalAmount,
        currency: 'MYR' as const,
      })
    );
  } catch (err) {
    const appErr = toAppError(err);
    return NextResponse.json(error(appErr.message), { status: appErr.status });
  }
}
