import { NextRequest, NextResponse } from 'next/server';
import { requireAuth } from '@/lib/auth/session';
import { ok, error } from '@/lib/api/response';
import { toAppError } from '@/lib/errors';
import { validateBody, withRateLimit } from '@/lib/validation/middleware';
import { createOrderFromBookingsBodySchema } from '@/lib/validation/sale.schemas';
import { bookingRepository } from '@/server/repositories/booking.repository';
import { logActivity } from '@/server/services/activity.service';

/**
 * POST /api/sale/orders/from-bookings
 *
 * Converts an explicit set of CONFIRMED `Booking` rows for one customer in
 * one live session into a single `Order` with consolidated `OrderItem` rows.
 *
 * Idempotent: same body (same `bookingIds`) returns the existing Order
 * once it has been created. Built on `Booking.idempotencyKey` /
 * `Order.idempotencyKey` deterministic key:
 *   sale-conv:{shopId}:{liveSessionId}:{customerId}:{sortedBookingIdsHash16}
 *
 * Auth: OWNER or MANAGER only. CHAT_SUPPORT and WAREHOUSE forbidden per
 * RBAC §9 in dissent doc 2026-04-06-sale-mvp-dissent.md.
 *
 * No customer-facing message is generated by this route. Phase 1 = no
 * auto-send (Boss decision Q7). Future Commit 2J+ will add a separate
 * summary endpoint that returns localized text for admin to copy/preview.
 *
 * Repository contract:
 *   src/server/repositories/booking.repository.ts → convertToOrder()
 *
 * Design refs:
 * - docs/superpowers/2026-05-09-booking-to-order-conversion-dissent.md
 * - docs/superpowers/2026-04-06-sale-mvp-dissent.md
 */
export async function POST(request: NextRequest): Promise<NextResponse> {
  return withRateLimit(request, async () => {
    try {
      const user = await requireAuth();

      if (!user.shopId) {
        return NextResponse.json(error('No shop associated with your account'), {
          status: 403,
        });
      }

      if (!['OWNER', 'MANAGER'].includes(user.role)) {
        return NextResponse.json(error('Insufficient permissions'), { status: 403 });
      }

      const bodyResult = await validateBody(request, createOrderFromBookingsBodySchema);
      if ('error' in bodyResult) return bodyResult.error;

      const { liveSessionId, customerId, bookingIds } = bodyResult.data;

      // PR 2 AR-3: V1 legacy path requires liveSessionId + customerId;
      // V2 omnichannel path requires neither (only bookingIds). Schema
      // refine() enforces "either both or neither". Pass only what was
      // provided so repository dispatcher routes correctly. Repository
      // gates V2 behind ALLOW_BOOKINGIDS_ONLY_CONVERSION flag.
      const result = await bookingRepository.convertToOrder({
        shopId: user.shopId,
        ...(liveSessionId !== undefined ? { liveSessionId } : {}),
        ...(customerId !== undefined ? { customerId } : {}),
        changedById: user.id,
        bookingIds,
      });

      // Activity log only on real conversion (not idempotent re-call) per
      // existing pattern (see /api/sale/bookings/.../confirm route).
      if (!result.idempotent) {
        logActivity({
          shopId: user.shopId,
          userId: user.id,
          userName: user.name,
          action: 'ORDER_CREATED_FROM_BOOKINGS',
          entity: 'order',
          entityId: result.orderId,
          description: `Order ${result.orderNumber} created from ${result.bookingCount} confirmed booking(s)`,
          metadata: {
            orderId: result.orderId,
            orderNumber: result.orderNumber,
            bookingCount: result.bookingCount,
            bookingIds: [...result.bookingIds],
            totalAmount: result.totalAmount,
            liveSessionId: liveSessionId ?? null,
            customerId: customerId ?? null,
            conversionPath: liveSessionId !== undefined ? 'v1' : 'v2',
          },
        }).catch(() => {});
      }

      return NextResponse.json(
        ok({
          orderId: result.orderId,
          orderNumber: result.orderNumber,
          status: result.status,
          idempotent: result.idempotent,
          bookingCount: result.bookingCount,
          bookingIds: [...result.bookingIds],
          totalAmount: result.totalAmount,
          currency: 'MYR' as const,
        })
      );
    } catch (err) {
      const appErr = toAppError(err);
      return NextResponse.json(error(appErr.message), { status: appErr.status });
    }
  });
}
